bulker:
  volumes:
   - $HOME
  envvars:
   - DISPLAY
  registry_url: http://bwbioinfo.github.io/bulker/
  shell_path: ${SHELL}
  shell_rc: $HOME/.zshrc
  rcfile: templates/start.sh
  rcfile_strict: templates/start_strict.sh
  default_crate_folder: ${HOME}/bulker_crates
  singularity_image_folder: ${HOME}/simages
  container_engine: singularity
  default_namespace: bulker
  executable_template: templates/singularity_executable.jinja2
  shell_template: templates/singularity_shell.jinja2
  build_template: templates/singularity_build.jinja2
  crates:
    seqtools:
      seqtools:
        default: ${HOME}/bulker_crates/seqtools/seqtools/default
    devtools:
      nf:
        default: ${HOME}/bulker_crates/devtools/nf/default
